


server:
  port: 11881

matchengine:
  symbols:
    - btc-usdt
    - eth-usdt
#    - eth-btc
#    - eos-usdt
#    - usdt-usd
  dbDisk:
    directory: matchengine
    limit: 20
  backup:
    executetimes: 10
  orderdb:
    host: ws://localhost:17711/orderdb